version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      
    dependencies:
      pre:
        - apt install make
        - apt install build-essential
     
    steps:
      - checkout
      - run:
          name: Compile the software
          command: cmake
      - run:
          name: print the date
          command: date

